### ISSUE TITLE
total size of new array must be unchanged when running all_in_one.py

### ISSUE THREAD

**Issue by HbueSky** [taki0112/CASED-Tensorflow#1]
Traceback (most recent call last):
  File "/home/s/PycharmProjects/CASED-Tensorflow-master/preprocessing/all_in_one.py", line 104, in <module>
    patch_stride(label, voxelCoord, offset, nodule_label_list, patch_flag=False)
  File "/home/s/PycharmProjects/CASED-Tensorflow-master/preprocessing/preprocess_utils.py", line 137, in patch_stride
    get_patch(image, coords, offset, nodule_list, patch_flag)
  File "/home/s/PycharmProjects/CASED-Tensorflow-master/preprocessing/preprocess_utils.py", line 91, in get_patch
    output = np.reshape(output, (label_size, label_size, label_size, 2))
  File "/home/s/anaconda2/envs/tensorflow/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 224, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged

**Comment by dongqing065269** [comment]
hello ,when i run the h5py_patch.py, i got a problem of "too many indices for array",do you know how to solve it? thanks very much!

**Comment by playyalp1** [comment]
@dongqing065269  Have you solved this problem？

**Comment by dongqing065269** [comment]
I did not solve it,  i want to get the lung patch,but i didn't solve this probelm.
